# Generated by Django 4.2.11 on 2026-06-07 17:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('gestational_week', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('village', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UrineTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('protein_class', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('trigger_systolic', models.FloatField()),
                ('trigger_diastolic', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urine_tests', to='preeclampsense.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BPMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('systolic', models.FloatField()),
                ('diastolic', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('spo2', models.FloatField(default=98)),
                ('risk_score', models.FloatField(default=0)),
                ('risk_level', models.CharField(default='normal', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_measurements', to='preeclampsense.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_name', models.CharField(max_length=120)),
                ('village', models.CharField(blank=True, max_length=120)),
                ('gestational_week', models.IntegerField()),
                ('systolic', models.FloatField()),
                ('diastolic', models.FloatField()),
                ('protein_class', models.IntegerField()),
                ('maps_url', models.URLField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='preeclampsense.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
